# Generated by Django 2.2.10 on 2020-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField()),
                ('address', models.CharField(max_length=300)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
