# Generated by Django 2.2.10 on 2020-09-08 12:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_auto_20200905_1759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='r',
            new_name='Register',
        ),
    ]
