# Generated by Django 2.2.10 on 2020-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_images', models.ImageField(upload_to='blog/')),
                ('blog_content', models.CharField(max_length=500)),
                ('blog_category', models.CharField(max_length=50)),
            ],
        ),
    ]
