# Generated by Django 2.2.10 on 2020-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_images', models.ImageField(upload_to='blog/')),
                ('blog_content', models.CharField(max_length=500)),
                ('blog_category', models.CharField(max_length=50)),
                ('blog_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Blog_Content',
        ),
    ]
