# Generated by Django 2.2.10 on 2020-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_pic', models.ImageField(upload_to='')),
                ('watch_detail', models.CharField(max_length=50)),
                ('watch_price', models.CharField(max_length=10)),
            ],
        ),
    ]
