# Generated by Django 2.2.10 on 2020-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200925_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='watch_price',
            field=models.IntegerField(),
        ),
    ]
