# Generated by Django 2.2.10 on 2020-10-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201004_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='watch_price',
            field=models.CharField(max_length=10),
        ),
    ]
