# Generated by Django 2.2.10 on 2020-10-06 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_order_list'),
        ('shop', '0005_auto_20201004_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Register')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Watch')),
            ],
        ),
    ]
