# Generated by Django 2.2.10 on 2020-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('detail', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
